### ISSUE TITLE
Getting a Flash security error

### ISSUE THREAD

**Issue by kamcknig** [denisdanielyan/as3-Application-Only-Twitter#6]
It works fine as long as the file is local and is trusted. But if it's not trusted in the global Flash settings or it's run from my server, I get the security error.

Error #2044: Unhandled securityError:. text=Error #2048: Security sandbox violation: http://kamcknight.net/freelance/twitter-application-only-tlssocket.swf cannot load data from api.twitter.com:443.

**Comment by denisdanielyan** [comment]
the Problem is, that the module has never been designed to run on a webserver but as a desktop / mobile app.
AFAIK this issue cannot be solved as the app get's data from twitter and of course twitter does not allow us to set a crossdomain-policy file.
